command_prefix = "!"

[[server]]

address = "irc.freenode.net:6667"
channels = ["#ucsd"]

[[command]]

name = "help"
script = "commands/help.js"

[[command]]

name = "quit"
script = "commands/quit.js"

[[command]]

name = "js"
script = "commands/js.js"
